FROM node:14.16.1-alpine as build

WORKDIR /usr/src/folder_com

COPY package.json package.json

RUN npm config set unsafe-perm true
RUN npm install -g create-react-app
RUN npm install --silent

COPY . .

RUN npm run build

EXPOSE 3000
CMD npm run start
#CMD node src/App.js
